[package]
name = "rawdio"
version = "0.1.0"
authors = ["James Elford <james.p.elford@gmail.com>"]
edition = "2018"

[dependencies]
cpal = "~0.13.1"
anyhow = {version = "^1.0", optional = true}
clap = {version = "^2.33", optional = true}


[features]
default = ["anyhow", "clap"]
