[package]
name = "speech-streamer"
version = "0.1.0"
authors = ["James Elford <james.p.elford@gmail.com>"]
edition = "2018"
links = "deepspeech"
build = "build.rs"

[dependencies]
cpal = "0.13.1"
deepspeech = { path = "deepspeech-rs" }

